var scr_templates = [
    ["Template 1", "32px,icon-white,pad,opacity", "no"],
    ["Template 2", "32px,icon-white,opacity", "no"],
    ["Template 3", "32px,icon-white,circle,pad,opacity", "no"],
    ["Template 4", "32px,icon-white,squircle,pad,opacity", "no"],
    ["Template 5", "32px,icon-white,diamond,pad,opacity", "no"],
    ["Template 6", "32px,icon-white,ribbon,pad,opacity", "no"],
    ["Template 7", "32px,icon-white,drop,pad,opacity", "no"],
    ["Template 8", "32px,icon-dark,bg-white,circle,pad,opacity", "no"],
    ["Template 9", "32px,icon-white,bg-dark,circle,pad,opacity", "no"],
    ["Template 10", "32px,icon-dark,bg-none,pad,opacity", "no"],
    ["Template 11", "32px,bg-none,pad,opacity", "no"],
    ["Template 12", "32px,bdr-md,bg-none,pad,opacity", "no"],
    ["Template 13", "32px,bdr-md,circle,bg-none,pad,opacity", "no"],
    ["Template 14", "32px,bg-white,bdr-md,bdr-grey,circle,pad,opacity", "no"],
    ["Template 15", "32px,icon-dark,bg-white,bdr-md,bdr-dark,circle,pad,opacity", "no"],
    ["Template 16", "32px,bg-white,bdr-md,bdr-dark,squircle-2,pad,opacity", "no"],
    ["Template 17", "32px,icon-white,pad,opacity", "in"],
    ["Template 18", "32px,icon-white,circle,pad,opacity", "in"],
    ["Template 19", "32px,icon-white,squircle-2,pad,opacity", "in"],
    ["Template 20", "32px,icon-white,pad", "out"],
    ["Template 21", "32px,icon-white,squircle,fluid,pad,opacity", "no"],
    ["Template 22", "32px,icon-white,fluid,opacity", "no"],
    ["Template 23", "32px,icon-white,bg-dark,fluid,pad,opacity", "no"],
    ["Template 24", "32px,bg-none,fluid,opacity", "no"],
    ["Template 25", "32px,bg-none,fluid,opacity", "in"],
    
    ["", "pad,count-4,bg-none,icon-grey,opacity,32px", "in"],
    ["", "pad,count-2,bg-none,bdr-sm,opacity,32px", "in"],
    ["", "count-3,bg-dark,icon-white,opacity,32px", "in"],
    ["", "pad,count-1,bg-none,opacity,32px", "in"],
    ["", "pad,count-1,bg-none,bdr-dark,bdr-md,icon-dark,opacity,32px", "in"],
    ["", "pad,count-1,icon-white,opacity,circle,32px", "in"],
    ["", "count-1,icon-white,opacity,32px", "in"],
    ["", "pad,count-4,icon-white,opacity,32px", "in"],
    ["", "sw-2,count-1,icon-white,no-icon,fluid,opacity,32px", "in"],
    ["", "pad,sw-icon-1,count-1,bdr-dark,bdr-md,icon-white,no-icon,opacity,32px", "in"],
    ["", "pad,count-1,bg-none,bdr-dark,bdr-md,icon-dark,no-icon,opacity,squircle-2,32px", "in"],
    ["", "pad,count-1,bg-none,bdr-md,no-icon,opacity,32px", "in"],
    ["", "pad,count-1,icon-white,no-icon,opacity,32px", "in"],
    ["", "pad,count-3,icon-white,fluid,sink,32px", "in"],
    ["", "pad,count-3,bg-white,bdr-sm,opacity,squircle-2,32px", "in"],
    ["", "pad,count-1,bg-dark,icon-white,fade-white,squircle-2,32px", "in"],
    ["", "pad,count-4,bg-none,zoom,32px", "in"],
    ["", "pad,count-3,icon-white,float,32px", "in"],
    ["", "pad,count-1,bg-none,icon-grey,float,32px", "in"],
    ["", "pad,sw-1,count-1,bg-white,float,circle,32px", "in"],
    ["", "pad,sw-2,count-1,bg-grey,icon-dark,opacity,squircle-2,32px", "in"],
    ["", "pad,count-1,bg-white,bdr-dark,bdr-md,zoom,squircle-2,32px", "in"],
    ["", "sw-2,count-1,icon-white,float,32px", "in"],
    ["", "pad,count-1,bg-none,bdr-md,zoom,squircle-2,32px", "in"],
    ["", "pad,count-1,bg-none,opacity,32px", "in"],
    ["", "pad,sw-1,count-2,bg-none,bdr-md,zoom,circle,32px", "in"],
    ["", "pad,count-1,bg-none,bdr-md,zoom,ribbon,32px", "in"],
    ["", "pad,count-1,bg-dark,bdr-dark,icon-white,float,ribbon,32px", "in"],
    ["", "pad,sw-icon-1,count-1,bdr-dark,bdr-md,icon-white,zoom,32px", "in"],
    ["", "pad,count-1,bg-none,bdr-dark,bdr-md,icon-dark,fade-black,squircle-2,32px", "in"],
    ["", "pad,count-1,bg-none,bdr-md,zoom,32px", "in"],
    ["", "pad,sw-2,count-1,bg-white,icon-dark,fade-black,circle,32px", "in"],
    ["", "pad,count-1,icon-white,fluid,float,circle,32px", "in"],
    ["", "pad,count-1,icon-white,fluid,fade-white,squircle-2,32px", "in"],
    ["", "pad,count-1,bg-white,bdr-md,fluid,zoom,32px", "in"],
    ["", "sw-2,count-1,icon-white,fluid,float,32px", "in"],
    ["", "pad,count-1,icon-white,zoom,circle,32px", "in"],
    ["", "pad,sw-1,count-1,bg-white,opacity,circle,32px", "in"],
    ["", "pad,count-1,bg-none,bdr-md,opacity,32px", "in"],
    ["", "pad,count-1,bg-none,opacity,32px", "in"],
    ["", "pad,sw-icon-1,count-1,icon-white,opacity,squircle-2,32px", "in"],
    ["", "pad,count-4,bg-none,icon-dark,zoom,32px", "in"],
    ["", "pad,sw-icon-1,count-2,icon-white,zoom,32px", "in"],
    
];